server:
  port: 8081
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        cluster-name: SH
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS