server:
  port: 8080
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        cluster-name: SH # 设置集群名称
        ephemeral: false # 设置为永久实例
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS